// Centralized Mock School Dataset for Govt. High School, Baripada (Odisha)
// Classes 6 to 10 (Sections A & B)

export const SCHOOL_INFO = {
  id: 'sch-01',
  name: 'Govt. High School, Baripada',
  udiseCode: '21070104802',
  district: 'Mayurbhanj',
  block: 'Baripada Sadar',
  cluster: 'Baripada Town',
  academicYear: '2026-2027',
  totalStudents: 486,
  totalTeachers: 18,
  totalClasses: 10,
  hmName: 'Dr. B. K. Mohapatra',
  contactEmail: 'hm.baripada@ruraledu.odisha.gov.in',
  contactPhone: '+91 6792 252104',
};

export const MOCK_CLASSES = [
  {
    id: 'cls-6a',
    grade: 6,
    section: 'A',
    displayName: 'Class 6-A',
    classTeacherId: 'tch-004',
    classTeacherName: 'Smt. Minati Murmu',
    studentCount: 46,
    attendanceRate: 92.4,
    avgPerformance: 78.2,
    atRiskCount: 2,
    topSubject: 'Odia Literature',
    needSupportSubject: 'Mathematics',
    roomNo: 'Room 101',
  },
  {
    id: 'cls-6b',
    grade: 6,
    section: 'B',
    displayName: 'Class 6-B',
    classTeacherId: 'tch-005',
    classTeacherName: 'Shri Bikash Senapati',
    studentCount: 46,
    attendanceRate: 89.6,
    avgPerformance: 74.0,
    atRiskCount: 3,
    topSubject: 'Environmental Studies',
    needSupportSubject: 'English',
    roomNo: 'Room 102',
  },
  {
    id: 'cls-7a',
    grade: 7,
    section: 'A',
    displayName: 'Class 7-A',
    classTeacherId: 'tch-001',
    classTeacherName: 'Shri Rameshwar Sahoo',
    studentCount: 49,
    attendanceRate: 88.0,
    avgPerformance: 72.5,
    atRiskCount: 4,
    topSubject: 'Science',
    needSupportSubject: 'Mathematics',
    roomNo: 'Room 103',
  },
  {
    id: 'cls-7b',
    grade: 7,
    section: 'B',
    displayName: 'Class 7-B',
    classTeacherId: 'tch-006',
    classTeacherName: 'Smt. Subhashree Dash',
    studentCount: 49,
    attendanceRate: 86.2,
    avgPerformance: 69.8,
    atRiskCount: 3,
    topSubject: 'Social Science',
    needSupportSubject: 'Mathematics',
    roomNo: 'Room 104',
  },
  {
    id: 'cls-8a',
    grade: 8,
    section: 'A',
    displayName: 'Class 8-A',
    classTeacherId: 'tch-002',
    classTeacherName: 'Dr. Pravat Ranjan Jena',
    studentCount: 52,
    attendanceRate: 85.5,
    avgPerformance: 67.4,
    atRiskCount: 4,
    topSubject: 'Odia',
    needSupportSubject: 'Science',
    roomNo: 'Room 201',
  },
  {
    id: 'cls-8b',
    grade: 8,
    section: 'B',
    displayName: 'Class 8-B',
    classTeacherId: 'tch-007',
    classTeacherName: 'Shri Alok Kumar Nayak',
    studentCount: 52,
    attendanceRate: 83.1,
    avgPerformance: 68.9,
    atRiskCount: 4,
    topSubject: 'Social Studies',
    needSupportSubject: 'English',
    roomNo: 'Room 202',
  },
  {
    id: 'cls-9a',
    grade: 9,
    section: 'A',
    displayName: 'Class 9-A',
    classTeacherId: 'tch-003',
    classTeacherName: 'Smt. Geeta Rani Behera',
    studentCount: 48,
    attendanceRate: 90.1,
    avgPerformance: 75.6,
    atRiskCount: 2,
    topSubject: 'Physical Science',
    needSupportSubject: 'Odia Grammar',
    roomNo: 'Room 203',
  },
  {
    id: 'cls-9b',
    grade: 9,
    section: 'B',
    displayName: 'Class 9-B',
    classTeacherId: 'tch-008',
    classTeacherName: 'Shri Manoranjan Giri',
    studentCount: 48,
    attendanceRate: 88.4,
    avgPerformance: 72.8,
    atRiskCount: 1,
    topSubject: 'Life Science',
    needSupportSubject: 'Mathematics',
    roomNo: 'Room 204',
  },
  {
    id: 'cls-10a',
    grade: 10,
    section: 'A',
    displayName: 'Class 10-A',
    classTeacherId: 'tch-009',
    classTeacherName: 'Shri Pradeep Kumar Rout',
    studentCount: 48,
    attendanceRate: 92.8,
    avgPerformance: 80.4,
    atRiskCount: 1,
    topSubject: 'Mathematics',
    needSupportSubject: 'English',
    roomNo: 'Room 301',
  },
  {
    id: 'cls-10b',
    grade: 10,
    section: 'B',
    displayName: 'Class 10-B',
    classTeacherId: 'tch-010',
    classTeacherName: 'Smt. Jayashree Tripathy',
    studentCount: 48,
    attendanceRate: 89.2,
    avgPerformance: 78.0,
    atRiskCount: 0,
    topSubject: 'Science',
    needSupportSubject: 'Social Studies',
    roomNo: 'Room 302',
  },
];

export const MOCK_TEACHERS = [
  {
    id: 'tch-001',
    name: 'Shri Rameshwar Sahoo',
    designation: 'Senior Teacher (Mathematics)',
    qualification: 'M.Sc., B.Ed.',
    primarySubject: 'Mathematics',
    secondarySubject: 'Physical Science',
    assignedClasses: ['Class 7-A', 'Class 8-A', 'Class 9-B'],
    classTeacherOf: 'Class 7-A',
    attendanceRate: 98.0,
    totalStudents: 149,
    avgClassPerformance: 74.2,
    status: 'Active',
    experienceYears: 14,
    email: 'rameshwar.s@ruraledu.odisha.gov.in',
    phone: '+91 94371 82901',
    joinDate: '2012-07-15',
  },
  {
    id: 'tch-002',
    name: 'Dr. Pravat Ranjan Jena',
    designation: 'TG Teacher (Science)',
    qualification: 'Ph.D., B.Ed.',
    primarySubject: 'Science',
    secondarySubject: 'Life Science',
    assignedClasses: ['Class 8-A', 'Class 9-A', 'Class 10-A'],
    classTeacherOf: 'Class 8-A',
    attendanceRate: 96.5,
    totalStudents: 148,
    avgClassPerformance: 76.8,
    status: 'Active',
    experienceYears: 11,
    email: 'pravat.jena@ruraledu.odisha.gov.in',
    phone: '+91 94373 55210',
    joinDate: '2015-09-01',
  },
  {
    id: 'tch-003',
    name: 'Smt. Geeta Rani Behera',
    designation: 'Senior Teacher (Odia & Sanskrit)',
    qualification: 'M.A. (Odia), B.Ed.',
    primarySubject: 'Odia',
    secondarySubject: 'Sanskrit',
    assignedClasses: ['Class 6-A', 'Class 7-A', 'Class 9-A', 'Class 10-A'],
    classTeacherOf: 'Class 9-A',
    attendanceRate: 99.0,
    totalStudents: 191,
    avgClassPerformance: 82.4,
    status: 'Active',
    experienceYears: 18,
    email: 'geeta.behera@ruraledu.odisha.gov.in',
    phone: '+91 98610 44321',
    joinDate: '2008-03-20',
  },
  {
    id: 'tch-004',
    name: 'Smt. Minati Murmu',
    designation: 'TG Teacher (Arts & English)',
    qualification: 'M.A. (English), B.Ed.',
    primarySubject: 'English',
    secondarySubject: 'Social Studies',
    assignedClasses: ['Class 6-A', 'Class 6-B', 'Class 7-B'],
    classTeacherOf: 'Class 6-A',
    attendanceRate: 95.0,
    totalStudents: 141,
    avgClassPerformance: 73.0,
    status: 'Active',
    experienceYears: 8,
    email: 'minati.murmu@ruraledu.odisha.gov.in',
    phone: '+91 97772 19834',
    joinDate: '2018-06-12',
  },
  {
    id: 'tch-005',
    name: 'Shri Bikash Senapati',
    designation: 'TG Teacher (Science & Math)',
    qualification: 'B.Sc., B.Ed.',
    primarySubject: 'Mathematics',
    secondarySubject: 'Science',
    assignedClasses: ['Class 6-A', 'Class 6-B', 'Class 7-B'],
    classTeacherOf: 'Class 6-B',
    attendanceRate: 94.0,
    totalStudents: 141,
    avgClassPerformance: 71.5,
    status: 'Active',
    experienceYears: 6,
    email: 'bikash.senapati@ruraledu.odisha.gov.in',
    phone: '+91 99381 72615',
    joinDate: '2020-01-08',
  },
  {
    id: 'tch-006',
    name: 'Smt. Subhashree Dash',
    designation: 'TG Teacher (Social Science)',
    qualification: 'M.A. (History), B.Ed.',
    primarySubject: 'Social Studies',
    secondarySubject: 'Odia',
    assignedClasses: ['Class 7-A', 'Class 7-B', 'Class 8-B'],
    classTeacherOf: 'Class 7-B',
    attendanceRate: 97.2,
    totalStudents: 150,
    avgClassPerformance: 75.1,
    status: 'Active',
    experienceYears: 9,
    email: 'subhashree.dash@ruraledu.odisha.gov.in',
    phone: '+91 94390 81273',
    joinDate: '2017-08-22',
  },
  {
    id: 'tch-007',
    name: 'Shri Alok Kumar Nayak',
    designation: 'TG Teacher (English)',
    qualification: 'M.A. (English), M.Ed.',
    primarySubject: 'English',
    secondarySubject: 'General Knowledge',
    assignedClasses: ['Class 8-A', 'Class 8-B', 'Class 9-B'],
    classTeacherOf: 'Class 8-B',
    attendanceRate: 93.5,
    totalStudents: 152,
    avgClassPerformance: 68.4,
    status: 'Active',
    experienceYears: 7,
    email: 'alok.nayak@ruraledu.odisha.gov.in',
    phone: '+91 98532 99401',
    joinDate: '2019-11-04',
  },
  {
    id: 'tch-008',
    name: 'Shri Manoranjan Giri',
    designation: 'TG Teacher (Science)',
    qualification: 'M.Sc. (Botany), B.Ed.',
    primarySubject: 'Life Science',
    secondarySubject: 'Environmental Studies',
    assignedClasses: ['Class 8-B', 'Class 9-A', 'Class 9-B'],
    classTeacherOf: 'Class 9-B',
    attendanceRate: 96.0,
    totalStudents: 148,
    avgClassPerformance: 77.3,
    status: 'Active',
    experienceYears: 10,
    email: 'manoranjan.giri@ruraledu.odisha.gov.in',
    phone: '+91 94378 12390',
    joinDate: '2016-04-14',
  },
  {
    id: 'tch-009',
    name: 'Shri Pradeep Kumar Rout',
    designation: 'Senior Teacher (Mathematics & Physics)',
    qualification: 'M.Sc. (Math), B.Ed.',
    primarySubject: 'Mathematics',
    secondarySubject: 'Physical Science',
    assignedClasses: ['Class 9-A', 'Class 10-A', 'Class 10-B'],
    classTeacherOf: 'Class 10-A',
    attendanceRate: 98.5,
    totalStudents: 144,
    avgClassPerformance: 81.2,
    status: 'Active',
    experienceYears: 16,
    email: 'pradeep.rout@ruraledu.odisha.gov.in',
    phone: '+91 94372 44109',
    joinDate: '2010-02-18',
  },
  {
    id: 'tch-010',
    name: 'Smt. Jayashree Tripathy',
    designation: 'TG Teacher (Social Science & Hindi)',
    qualification: 'M.A. (Pol Sci), B.Ed.',
    primarySubject: 'Social Studies',
    secondarySubject: 'Hindi',
    assignedClasses: ['Class 9-B', 'Class 10-A', 'Class 10-B'],
    classTeacherOf: 'Class 10-B',
    attendanceRate: 91.0,
    totalStudents: 144,
    avgClassPerformance: 79.5,
    status: 'On Leave',
    experienceYears: 12,
    email: 'jayashree.t@ruraledu.odisha.gov.in',
    phone: '+91 99374 81203',
    joinDate: '2014-07-25',
  },
];

export const MOCK_STUDENTS = [
  {
    id: 'std-001',
    name: 'Pooja Sethi',
    rollNo: '01',
    grade: 7,
    section: 'A',
    className: 'Class 7-A',
    gender: 'F',
    attendanceRate: 96,
    academicAverage: 88,
    learningProgress: 91,
    riskLevel: 'NORMAL',
    weakSubject: 'None',
    weakTopics: [],
    lastActive: 'Today, 10:45 AM',
    trend: 'up',
    parentName: 'Gopinath Sethi',
    parentContact: '+91 94371 99881',
    category: 'OBC',
    address: 'Baghra Road, Baripada',
    quizScores: { Math: 85, Science: 92, Odia: 94, English: 84, SocialScience: 86 },
  },
  {
    id: 'std-002',
    name: 'Priya Murmu',
    rollNo: '14',
    grade: 7,
    section: 'A',
    className: 'Class 7-A',
    gender: 'F',
    attendanceRate: 68,
    academicAverage: 44,
    learningProgress: 42,
    riskLevel: 'HIGH',
    weakSubject: 'Mathematics',
    weakTopics: ['Fractions & Decimals', 'Ratio & Proportion'],
    lastActive: 'Yesterday, 03:20 PM',
    trend: 'down',
    parentName: 'Salkhu Murmu',
    parentContact: '+91 97771 82341',
    category: 'ST',
    address: 'Deula, Ward 4, Baripada',
    quizScores: { Math: 38, Science: 52, Odia: 60, English: 45, SocialScience: 48 },
  },
  {
    id: 'std-003',
    name: 'Dibyaranjan Sahoo',
    rollNo: '27',
    grade: 8,
    section: 'B',
    className: 'Class 8-B',
    gender: 'M',
    attendanceRate: 72,
    academicAverage: 48,
    learningProgress: 46,
    riskLevel: 'HIGH',
    weakSubject: 'Science',
    weakTopics: ['Work & Energy Laws', 'Chemical Reactions'],
    lastActive: '2 days ago',
    trend: 'down',
    parentName: 'Niranjan Sahoo',
    parentContact: '+91 98612 77410',
    category: 'General',
    address: 'Kachery Road, Baripada',
    quizScores: { Math: 50, Science: 42, Odia: 64, English: 46, SocialScience: 51 },
  },
  {
    id: 'std-004',
    name: 'Sneha Majhi',
    rollNo: '09',
    grade: 6,
    section: 'A',
    className: 'Class 6-A',
    gender: 'F',
    attendanceRate: 79,
    academicAverage: 54,
    learningProgress: 56,
    riskLevel: 'MEDIUM',
    weakSubject: 'English',
    weakTopics: ['Tenses & Verb Forms', 'Reading Comprehension'],
    lastActive: 'Today, 09:15 AM',
    trend: 'up',
    parentName: 'Kishore Majhi',
    parentContact: '+91 99380 12049',
    category: 'ST',
    address: 'Takatpur, Baripada',
    quizScores: { Math: 58, Science: 60, Odia: 68, English: 48, SocialScience: 55 },
  },
  {
    id: 'std-005',
    name: 'Rakesh Soren',
    rollNo: '05',
    grade: 8,
    section: 'A',
    className: 'Class 8-A',
    gender: 'M',
    attendanceRate: 64,
    academicAverage: 46,
    learningProgress: 40,
    riskLevel: 'HIGH',
    weakSubject: 'Mathematics',
    weakTopics: ['Linear Equations', 'Algebraic Expressions'],
    lastActive: '3 days ago',
    trend: 'down',
    parentName: 'Durga Soren',
    parentContact: '+91 94391 66502',
    category: 'ST',
    address: 'Poda Astia, Baripada',
    quizScores: { Math: 40, Science: 48, Odia: 58, English: 42, SocialScience: 49 },
  },
  {
    id: 'std-006',
    name: 'Sunil Naik',
    rollNo: '02',
    grade: 7,
    section: 'A',
    className: 'Class 7-A',
    gender: 'M',
    attendanceRate: 98,
    academicAverage: 95,
    learningProgress: 98,
    riskLevel: 'NORMAL',
    weakSubject: 'None',
    weakTopics: [],
    lastActive: 'Today, 11:30 AM',
    trend: 'up',
    parentName: 'Baidhar Naik',
    parentContact: '+91 94370 12894',
    category: 'SC',
    address: 'Palbani, Baripada',
    quizScores: { Math: 98, Science: 96, Odia: 92, English: 94, SocialScience: 95 },
  },
  {
    id: 'std-007',
    name: 'Anjali Marandi',
    rollNo: '18',
    grade: 6,
    section: 'B',
    className: 'Class 6-B',
    gender: 'F',
    attendanceRate: 74,
    academicAverage: 52,
    learningProgress: 50,
    riskLevel: 'MEDIUM',
    weakSubject: 'Mathematics',
    weakTopics: ['Number Systems', 'Basic Geometry'],
    lastActive: 'Yesterday, 04:10 PM',
    trend: 'neutral',
    parentName: 'Hopna Marandi',
    parentContact: '+91 97775 88912',
    category: 'ST',
    address: 'Indapahi, Baripada',
    quizScores: { Math: 46, Science: 55, Odia: 65, English: 50, SocialScience: 54 },
  },
  {
    id: 'std-008',
    name: 'Manish Kumar Behera',
    rollNo: '12',
    grade: 9,
    section: 'A',
    className: 'Class 9-A',
    gender: 'M',
    attendanceRate: 92,
    academicAverage: 81,
    learningProgress: 84,
    riskLevel: 'NORMAL',
    weakSubject: 'Odia Grammar',
    weakTopics: ['Sandhi & Samasa'],
    lastActive: 'Today, 08:50 AM',
    trend: 'up',
    parentName: 'Rabindra Behera',
    parentContact: '+91 98615 44921',
    category: 'SC',
    address: 'Khandadeula, Baripada',
    quizScores: { Math: 88, Science: 86, Odia: 72, English: 82, SocialScience: 85 },
  },
  {
    id: 'std-009',
    name: 'Lipsa Biswal',
    rollNo: '08',
    grade: 9,
    section: 'B',
    className: 'Class 9-B',
    gender: 'F',
    attendanceRate: 85,
    academicAverage: 62,
    learningProgress: 65,
    riskLevel: 'LOW',
    weakSubject: 'Mathematics',
    weakTopics: ['Trigonometry Basics'],
    lastActive: 'Yesterday, 02:00 PM',
    trend: 'up',
    parentName: 'Dillip Biswal',
    parentContact: '+91 94372 90118',
    category: 'General',
    address: 'Station Road, Baripada',
    quizScores: { Math: 56, Science: 68, Odia: 74, English: 64, SocialScience: 66 },
  },
  {
    id: 'std-010',
    name: 'Gourav Mohanty',
    rollNo: '03',
    grade: 10,
    section: 'A',
    className: 'Class 10-A',
    gender: 'M',
    attendanceRate: 95,
    academicAverage: 89,
    learningProgress: 94,
    riskLevel: 'NORMAL',
    weakSubject: 'None',
    weakTopics: [],
    lastActive: 'Today, 11:00 AM',
    trend: 'up',
    parentName: 'Sanjay Mohanty',
    parentContact: '+91 94374 81290',
    category: 'General',
    address: 'Bada Bazar, Baripada',
    quizScores: { Math: 94, Science: 92, Odia: 86, English: 90, SocialScience: 88 },
  },
  {
    id: 'std-011',
    name: 'Kavita Hembram',
    rollNo: '22',
    grade: 8,
    section: 'A',
    className: 'Class 8-A',
    gender: 'F',
    attendanceRate: 70,
    academicAverage: 51,
    learningProgress: 49,
    riskLevel: 'MEDIUM',
    weakSubject: 'Science',
    weakTopics: ['Cell Structure', 'Microorganisms'],
    lastActive: '2 days ago',
    trend: 'down',
    parentName: 'Chunaram Hembram',
    parentContact: '+91 97779 12384',
    category: 'ST',
    address: 'Murgabadi, Baripada',
    quizScores: { Math: 52, Science: 45, Odia: 62, English: 54, SocialScience: 56 },
  },
  {
    id: 'std-012',
    name: 'Sambit Kumar Panda',
    rollNo: '15',
    grade: 10,
    section: 'B',
    className: 'Class 10-B',
    gender: 'M',
    attendanceRate: 88,
    academicAverage: 76,
    learningProgress: 79,
    riskLevel: 'NORMAL',
    weakSubject: 'Social Studies',
    weakTopics: ['Indian Nationalism History'],
    lastActive: 'Today, 10:15 AM',
    trend: 'neutral',
    parentName: 'Prasanna Panda',
    parentContact: '+91 98611 20984',
    category: 'General',
    address: 'Meher Colony, Baripada',
    quizScores: { Math: 82, Science: 78, Odia: 80, English: 74, SocialScience: 66 },
  },
];

export const MOCK_AT_RISK_RECORDS = [
  {
    id: 'risk-01',
    studentId: 'std-002',
    studentName: 'Priya Murmu',
    rollNo: '14',
    className: 'Class 7-A',
    grade: 7,
    section: 'A',
    riskTier: 'HIGH',
    attendanceScore: 68,
    academicScore: 44,
    engagementScore: 40,
    weakSubject: 'Mathematics',
    weakTopics: ['Fractions & Decimals', 'Ratio & Proportion'],
    primaryCause: 'Repeated quiz failure in fractions + 12 days consecutive absence post harvest festival.',
    recommendedIntervention: 'Fractions visual remedial kit & bilingual peer practice with Pooja Sethi.',
    assignedTeacher: 'Shri Rameshwar Sahoo',
    status: 'Intervention Active',
    notes: 'Tablet assigned with offline Odia-medium fraction video modules. Parent meeting conducted on Feb 10.',
    lastUpdated: '2026-02-12',
  },
  {
    id: 'risk-02',
    studentId: 'std-003',
    studentName: 'Dibyaranjan Sahoo',
    rollNo: '27',
    className: 'Class 8-B',
    grade: 8,
    section: 'B',
    riskTier: 'HIGH',
    attendanceScore: 72,
    academicScore: 48,
    engagementScore: 45,
    weakSubject: 'Science',
    weakTopics: ['Work & Energy Laws', 'Chemical Reactions'],
    primaryCause: 'Missed Science lab experiments and scored < 45% in last two chapter quizzes.',
    recommendedIntervention: 'Virtual lab simulations & weekly concept checkpoint with Dr. Jena.',
    assignedTeacher: 'Dr. Pravat Ranjan Jena',
    status: 'Pending Review',
    notes: 'Teacher to schedule 2x weekly after-school lab remedial sessions.',
    lastUpdated: '2026-02-14',
  },
  {
    id: 'risk-03',
    studentId: 'std-005',
    studentName: 'Rakesh Soren',
    rollNo: '05',
    className: 'Class 8-A',
    grade: 8,
    section: 'A',
    riskTier: 'HIGH',
    attendanceScore: 64,
    academicScore: 46,
    engagementScore: 38,
    weakSubject: 'Mathematics',
    weakTopics: ['Linear Equations', 'Algebraic Expressions'],
    primaryCause: 'Chronic absenteeism (attendance 64%) and incomplete homework submissions.',
    recommendedIntervention: 'Home visit by Class Teacher & localized remedial workbook.',
    assignedTeacher: 'Dr. Pravat Ranjan Jena',
    status: 'Pending Review',
    notes: 'Guardian notified via SMS and phone. Pending HM sign-off for attendance support grant.',
    lastUpdated: '2026-02-15',
  },
  {
    id: 'risk-04',
    studentId: 'std-004',
    studentName: 'Sneha Majhi',
    rollNo: '09',
    className: 'Class 6-A',
    grade: 6,
    section: 'A',
    riskTier: 'MEDIUM',
    attendanceScore: 79,
    academicScore: 54,
    engagementScore: 58,
    weakSubject: 'English',
    weakTopics: ['Tenses & Verb Forms', 'Reading Comprehension'],
    primaryCause: 'Struggles with English paragraph reading; good grasp in Odia medium.',
    recommendedIntervention: 'Daily audio comprehension exercises on tablet + story card reading.',
    assignedTeacher: 'Smt. Minati Murmu',
    status: 'Intervention Active',
    notes: 'Showing +6% score improvement after first 2 weeks of bilingual audio module.',
    lastUpdated: '2026-02-16',
  },
  {
    id: 'risk-05',
    studentId: 'std-007',
    studentName: 'Anjali Marandi',
    rollNo: '18',
    className: 'Class 6-B',
    grade: 6,
    section: 'B',
    riskTier: 'MEDIUM',
    attendanceScore: 74,
    academicScore: 52,
    engagementScore: 52,
    weakSubject: 'Mathematics',
    weakTopics: ['Number Systems', 'Basic Geometry'],
    primaryCause: 'Frequent morning delays due to transport issues from rural cluster.',
    recommendedIntervention: 'Peer study circle allocation and morning recap worksheets.',
    assignedTeacher: 'Shri Bikash Senapati',
    status: 'Intervention Active',
    notes: 'Assigned to Peer Study Circle Group 2 in Takatpur cluster.',
    lastUpdated: '2026-02-11',
  },
  {
    id: 'risk-06',
    studentId: 'std-011',
    studentName: 'Kavita Hembram',
    rollNo: '22',
    className: 'Class 8-A',
    grade: 8,
    section: 'A',
    riskTier: 'MEDIUM',
    attendanceScore: 70,
    academicScore: 51,
    engagementScore: 50,
    weakSubject: 'Science',
    weakTopics: ['Cell Structure', 'Microorganisms'],
    primaryCause: 'Low quiz retention in microscopic biology modules.',
    recommendedIntervention: 'Interactive 3D cell diagrams & weekly quiz re-takes.',
    assignedTeacher: 'Dr. Pravat Ranjan Jena',
    status: 'Resolved',
    notes: 'Remedial milestone achieved. Scored 64% in latest re-test.',
    lastUpdated: '2026-02-16',
  },
];

export const MOCK_ATTENDANCE_SUMMARY = {
  todayOverallRate: 88.2,
  totalEnrolled: 486,
  todayPresent: 429,
  todayAbsent: 57,
  monthlyAverage: 87.4,
  monthlyTrend: [
    { month: 'Sep', rate: 84.5 },
    { month: 'Oct', rate: 86.2 },
    { month: 'Nov', rate: 89.1 },
    { month: 'Dec', rate: 85.8 },
    { month: 'Jan', rate: 87.9 },
    { month: 'Feb (Current)', rate: 88.2 },
  ],
  classWiseToday: [
    { classId: 'cls-6a', className: 'Class 6-A', total: 46, present: 43, absent: 3, rate: 93.5 },
    { classId: 'cls-6b', className: 'Class 6-B', total: 46, present: 41, absent: 5, rate: 89.1 },
    { classId: 'cls-7a', className: 'Class 7-A', total: 49, present: 43, absent: 6, rate: 87.8 },
    { classId: 'cls-7b', className: 'Class 7-B', total: 49, present: 42, absent: 7, rate: 85.7 },
    { classId: 'cls-8a', className: 'Class 8-A', total: 52, present: 44, absent: 8, rate: 84.6 },
    { classId: 'cls-8b', className: 'Class 8-B', total: 52, present: 43, absent: 9, rate: 82.7 },
    { classId: 'cls-9a', className: 'Class 9-A', total: 48, present: 44, absent: 4, rate: 91.7 },
    { classId: 'cls-9b', className: 'Class 9-B', total: 48, present: 43, absent: 5, rate: 89.6 },
    { classId: 'cls-10a', className: 'Class 10-A', total: 48, present: 45, absent: 3, rate: 93.8 },
    { classId: 'cls-10b', className: 'Class 10-B', total: 48, present: 43, absent: 5, rate: 89.6 },
  ],
  chronicAbsenteeWatchlist: [
    { studentId: 'std-005', studentName: 'Rakesh Soren', className: 'Class 8-A', daysAbsentLast30Days: 9, attendanceRate: 64, contact: '+91 94391 66502' },
    { studentId: 'std-002', studentName: 'Priya Murmu', className: 'Class 7-A', daysAbsentLast30Days: 8, attendanceRate: 68, contact: '+91 97771 82341' },
    { studentId: 'std-011', studentName: 'Kavita Hembram', className: 'Class 8-A', daysAbsentLast30Days: 7, attendanceRate: 70, contact: '+91 97779 12384' },
    { studentId: 'std-003', studentName: 'Dibyaranjan Sahoo', className: 'Class 8-B', daysAbsentLast30Days: 6, attendanceRate: 72, contact: '+91 98612 77410' },
  ],
};

export const MOCK_PERFORMANCE_ANALYTICS = {
  schoolAverageScore: 73.6,
  passPercentage: 91.8,
  topPerformingSubject: 'Odia Literature (82.6%)',
  subjectRequiringSupport: 'Mathematics (68.4%)',
  subjectBreakdown: [
    { subject: 'Odia Literature', code: 'ODI', avgScore: 82.6, passRate: 97.2, highestScore: 98, lowestScore: 54, teacherName: 'Smt. Geeta Rani Behera', trend: '+4.2%' },
    { subject: 'Science (Physical & Life)', code: 'SCI', avgScore: 75.4, passRate: 91.5, highestScore: 96, lowestScore: 42, teacherName: 'Dr. Pravat Ranjan Jena', trend: '+2.8%' },
    { subject: 'Social Studies', code: 'SST', avgScore: 76.0, passRate: 93.0, highestScore: 95, lowestScore: 48, teacherName: 'Smt. Subhashree Dash', trend: '+1.5%' },
    { subject: 'English Language', code: 'ENG', avgScore: 70.2, passRate: 88.4, highestScore: 94, lowestScore: 40, teacherName: 'Shri Alok Kumar Nayak', trend: '+3.1%' },
    { subject: 'Mathematics', code: 'MTH', avgScore: 68.4, passRate: 84.2, highestScore: 98, lowestScore: 36, teacherName: 'Shri Rameshwar Sahoo', trend: '+1.9%' },
  ],
  assessmentComparison: [
    { type: 'Monthly Chapter Quizzes', average: 74.8, completionRate: 94.2, totalConducted: 42 },
    { type: 'Mid-Term Summative Exam', average: 71.5, completionRate: 98.4, totalConducted: 10 },
    { type: 'Homework & Lab Worksheets', average: 78.0, completionRate: 86.5, totalConducted: 128 },
  ],
};
